---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cloudopsdays-jp
spec:
  dnsNames:
  - '*.event.cloudopsdays.com'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: wildcard-cloudopsdays-com
