---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: wildcard-cloudopsdays-jp
spec:
  delegations:
    - secretName: wildcard-cloudopsdays-com
      targetNamespaces:
      - "*"
