apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mysql.yaml
- redis.yaml
- externalsecret.yaml
- ingress.yaml
- ../../../base
patchesStrategicMerge:
- deployment-dreamkast.yaml
images:
- name: public.ecr.aws/z5v6i5y3/dreamkast-ecs
  newTag: 2f467f8f9f52f301b2361c5be9e52896a7be3b69
namespace: dreamkast-dk-94
