apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mysql.yaml
- redis.yaml
- externalsecret.yaml
- ingress.yaml
- ../../../base
patchesStrategicMerge:
- deployment-dreamkast.yaml
images:
- name: public.ecr.aws/z5v6i5y3/dreamkast-ecs
  newTag: b0cb926d01374a8d97f2c0aa8c5ae34af07c6773
namespace: dreamkast-dk-78
