apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret.yaml
- ingress.yaml
- redis.yaml
- hpa.yaml
- ../../../base/
patchesStrategicMerge:
- deployment-dreamkast.yaml
images:
- name: public.ecr.aws/z5v6i5y3/dreamkast-ecs
  newTag: 64c099e2e1aab857df27c7a4c24eeee4cbb75e79
- name: public.ecr.aws/z5v6i5y3/dreamkast-ui
  newTag: 55974088bdb1b86781cd29dfe7fe148ec81868d8
namespace: dreamkast-staging
