apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret.yaml
- ingress.yaml
- redis.yaml
- hpa.yaml
- ../../../base/
patchesStrategicMerge:
- deployment-dreamkast.yaml
images:
- name: public.ecr.aws/z5v6i5y3/dreamkast-ecs
  newTag: 42a64a76fe35c16d1ff08e5759b66c89882f941a
- name: public.ecr.aws/z5v6i5y3/dreamkast-ui
  newTag: a3850f7d1c5a7cf9115092a150360bce03d2d449
namespace: dreamkast-staging
