apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret.yaml
- ingress.yaml
- redis.yaml
- hpa.yaml
- ../../../base/
patchesStrategicMerge:
- deployment-dreamkast.yaml
images:
- name: public.ecr.aws/z5v6i5y3/dreamkast-ecs
  newTag: 59f0139abaae5a47f74c8e715fac8eb5bfc7c89d
- name: public.ecr.aws/z5v6i5y3/dreamkast-ui
  newTag: 55974088bdb1b86781cd29dfe7fe148ec81868d8
namespace: dreamkast-staging
