---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: db-secret
spec:
  backendType: secretsManager
  data:
    - key: MyRDSSecret-isaS0oUHrQT1
      name: password
      property: password
    - key: MyRDSSecret-isaS0oUHrQT1
      name: username
      property: username
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: dreamkast-secret
spec:
  backendType: secretsManager
  data:
    - key: dreamkast/staging-env
      name: AUTH0_CLIENT_ID
      property: AUTH0_CLIENT_ID
    - key: dreamkast/staging-env
      name: AUTH0_CLIENT_SECRET
      property: AUTH0_CLIENT_SECRET
    - key: dreamkast/staging-env
      name: AUTH0_DOMAIN
      property: AUTH0_DOMAIN
    - key: dreamkast/staging-env
      name: AWS_ACCESS_KEY_ID
      property: AWS_ACCESS_KEY_ID
    - key: dreamkast/staging-env
      name: AWS_SECRET_ACCESS_KEY
      property: AWS_SECRET_ACCESS_KEY


