apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dreamkast-development-dk-12
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  destination:
    namespace: dreamkast-dk-12
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/app/dreamkast/overlays/development/dk-12
    repoURL: https://github.com/cloudopsdays/dreamkast-infra.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
