apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mysql.yaml
- redis.yaml
- externalsecret.yaml
- ingress.yaml
- ../../../base
patchesStrategicMerge:
- deployment-dreamkast.yaml
images:
- name: public.ecr.aws/z5v6i5y3/dreamkast-ecs
  newTag: accedbb1a3ecf3f2d9aed67d7940a015411b4e00
namespace: dreamkast-dk-8
