apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret.yaml
- ingress.yaml
- redis.yaml
- hpa.yaml
- ../../../base/
patchesStrategicMerge:
- deployment-dreamkast.yaml
images:
- name: public.ecr.aws/z5v6i5y3/dreamkast-ecs
  newTag: 95a007336eba5e6b352fbf7b8423d9b335ee88b0
- name: public.ecr.aws/z5v6i5y3/dreamkast-ui
  newTag: 559e020d6bba85c202939782a622d1067387dff4
namespace: dreamkast
