apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret.yaml
- ingress.yaml
- redis.yaml
- hpa.yaml
- ../../../base/
patchesStrategicMerge:
- deployment-dreamkast.yaml
images:
- name: public.ecr.aws/z5v6i5y3/dreamkast-ecs
  newTag: 398ee437bfd7a4947e6023b9d92d1e74d4226a53
- name: public.ecr.aws/z5v6i5y3/dreamkast-ui
  newTag: 559e020d6bba85c202939782a622d1067387dff4
namespace: dreamkast
