---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kubernetes-external-secrets
    repoURL: https://external-secrets.github.io/kubernetes-external-secrets/
    targetRevision: 6.1.0
    helm:
      parameters:
      - name: env.AWS_REGION
        value: ap-northeast-1
      - name: envVarsFromSecret.AWS_ACCESS_KEY_ID.secretKeyRef
        value: prod-secretmanager-credentials-secret
      - name: envVarsFromSecret.AWS_ACCESS_KEY_ID.key
        value: id
      - name: envVarsFromSecret.AWS_SECRET_ACCESS_KEY.secretKeyRef
        value: prod-secretmanager-credentials-secret
      - name: envVarsFromSecret.AWS_SECRET_ACCESS_KEY.key
        value: key
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
