apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: argocd-server-grpc
  namespace: argocd
spec:
  virtualhost:
    fqdn: argocd.dreamkast.cloudopsdays.jp
    tls:
      passthrough: true
  tcpproxy:
    services:
    - name: argocd-server
      port: 443
