apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mysql.yaml
- redis.yaml
- externalsecret.yaml
- ingress.yaml
- ../../../base
patchesStrategicMerge:
- deployment-dreamkast.yaml
images:
- name: public.ecr.aws/z5v6i5y3/dreamkast-ecs
  newTag: 840dc3809e0ba846fc9f49eff9c8947cc40dc139
namespace: dreamkast-dk-70
